{% set name = "aws_secretsmanager_caching" %}
{% set version = "1.1.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aws_secretsmanager_caching-{{ version }}.tar.gz
  sha256: 5cee2762bb89b72f3e5123feee8e45fbe44ffe163bfca08b28f27b2e2b7772e1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pytest-runner
    - setuptools-scm
    - pip
  run:
    - python >=3.6
    - botocore

test:
  imports:
    - aws_secretsmanager_caching
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/aws-secretsmanager-caching-python
  summary: Client-side AWS Secrets Manager caching library
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - mbestipa
